### PR TITLE
replace for(auto <var> to for(auto& <var>

### PR DESCRIPTION
**Pull request by aismann**
working with reference and not with copies
=> Performance issue

solve feature: #759

### CODE REVIEW

**Comment by DelinWorks** [comment]
Some objects cannot be directly referenced. they need to be copied instead, some iterators don't support referencing, and I think that's because of reference counting and that some objects might brake or leak if they're not copied.

**Comment by halx99** [comment]
I think the raw iterator don't needs change to `auto&`, just c++11 for-loop needs for non-pointer element like:
```cpp
for (auto& item : items)
```

**Comment by aismann** [comment]
> I think the raw iterator don't needs change to `auto&`, just c++11 for-loop needs for non-pointer element like:
> 
> ```c++
> for (auto& item : items)
>     item.callSomeMethod();
> ```

Correct! This one & was to much. Sorry. (removed it)

**Comment by aismann** [comment]
> I think the raw iterator don't needs change to `auto&`, just c++11 for-loop needs for non-pointer element like:
> 
> ```c++
> for (auto& item : items)
>     item.callSomeMethod();
> ```

@halx99 
BTW: also lyasio.cpp has a:                   for (auto item : channel_eps) +> can be changed to:  for (auto& item : channel_eps)

At the moment a don't changing anything on thirtparty folders

**Comment by halx99** [comment]
The `channel_ops` element is store as `pointer`, so don't need change

**Comment by aismann** [comment]
> The `channel_ops` element is store as `pointer`, so don't need change

I know. for` (auto item : channel_eps)` is no different to `for (auto& item : channel_eps)`
BUT: as an developer reading the sources its easier for understanding (its a ref not a copy).

**Comment by halx99** [comment]
Using c++11 `Universal Reference` maybe better like:
```cpp

std::vector<bool> items1 = {false};
for(auto&& item : items1) 
    item = true;

const std::vector<bool> items2 = {true};
for (auto && item : items2)
    printf("item=%d\n", (int)item);

```

**Comment by aismann** [comment]
> Using c++11 `Universal Reference` maybe better like:
> 
> ```c++
> std::vector<bool> items1 = {false};
> for(auto&& item : items1) 
>     item = true;
> 
> const std::vector<bool> items2 = {true};
> for (auto&& item : items2)
>     printf("item=%d\n", (int)item);
> ```
Should I change ALL `for (auto& <var1>: <var2>)` to `for (auto&& <var1>: <var2>)`

**Comment by halx99** [comment]
> > Using c++11 `Universal Reference` maybe better like:
> > ```c++
> > std::vector<bool> items1 = {false};
> > for(auto&& item : items1) 
> >     item = true;
> > 
> > const std::vector<bool> items2 = {true};
> > for (auto&& item : items2)
> >     printf("item=%d\n", (int)item);
> > ```
> 
> Should I change ALL `for (auto& <var1>: <var2>)` to `for (auto&& <var1>: <var2>)` ?

Yes, you can, the `Universal References` can handle both const or non-const containers.

**Comment by aismann** [comment]
Also for the 'extension' folder?

The ThirtParty folder will be untouched

**Comment by halx99** [comment]
> Also for the 'extension' folder?
> 
> The ThirtParty folder will be untouched

Yes, but should ignore `spine`, `fairygui`, `Live2D`

**Comment by aismann** [comment]
this extensions be untouched  (spine, Live2D has no such C++11 for loop):
image

**Review by halx99 — APPROVED** [review]

**Pull request merged**
