### PR TITLE
Support return type'ResourceData'

### PR DESCRIPTION
**Pull request by tkzcfc**
THIS PROJECT IS IN DEVELOPMENT MODE. Any pull requests should merge to branch `dev`, otherwise will be rejected immediately.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by rh101** [comment]
Doesn't everything in the "auto" folder get overwritten with the automatic binding creation script?  If that is the case, then this PR is not valid, and any entries need to be done somewhere else, perhaps in the "manual" folder.

**Comment by aismann** [comment]
BTW: /extensions/scripting/lua-bindings/auto should be disabled GitHub pull process. I have always uncheck it 😔

**Comment by rh101** [comment]
> BTW: /extensions/scripting/lua-bindings/auto should be disabled on GitHub pull process. I have always uncheck it 😔

Is there any specific reason you prefer to not have them in the repository?

It would mean users would need to generate the bindings themselves, and that's just an extra setup step that may cause problems, especially for newer users of the engine.

**Comment by aismann** [comment]
I mean the automatic generated stuff.

**Comment by rh101** [comment]
> I mean the automatic generated stuff, the automatic binding stuff

I understand, but I mean what is the reason not wanting that generated files to be in the repository?  The reason I ask is that the only time the auto-generated files are affected is if the engine code changes, and that is only relevant for engine developers, and not the majority of users of the engine.  Forcing typical users of the engine to generate the bindings seems like an unnecessary step.

**Comment by DelinWorks** [comment]
@rh101 I think what he meant is any pull requests that tries to modify lua-auto files should be denied, not actually removing the auto generated lua files from the repo

**Comment by rh101** [comment]
> PR to "automatic created stuff (executables, apk's, etc) should be permit.
> So `PRs like this` is not possible.

Sorry, I completely misunderstood what you meant in your initial post, but now I get what you mean, and I agree with you.

@DelinWorks I think I need to avoid posting so late at night 🤦‍♂️

**Comment by DelinWorks** [comment]
> > PR to "automatic created stuff (executables, apk's, etc) should be permit.
> > So `PRs like this` is not possible.
> 
> Sorry, I completely misunderstood what you meant in your initial post, but now I get what you mean, and I agree with you.
> 
> @DelinWorks I think I need to avoid posting so late at night 🤦‍♂️

Can you even do that in github?

**Pull request merged**
