### PR TITLE
Replace everything under `core`

### PR DESCRIPTION
**Pull request by DelinWorks**
Refer to #724

### CODE REVIEW

**Comment by halx99** [comment]
Your merge target branch is error, please close and recreate PR

**Comment by halx99** [comment]
> Your merge target branch is error, please close and recreate PR

I modify for  you, github is good

**Comment by halx99** [comment]
But, you shouldn't use github webpage `Fetch Upstream` since github will fetch default branch which I modifiy from `dev` to `release`, the right way for seperate PR is create new branch from `origin/dev`

**Comment by halx99** [comment]
> But, you shouldn't use github webpage `Fetch Upstream` since github will fetch default branch which I modifiy from `dev` to `release`, the right way for seperate PR is create new branch from `origin/dev`

This way, we can avoid many unnecessary commits histroy

**Comment by DelinWorks** [comment]
> Your merge target branch is error, please close and recreate PR

How about now? I remerged the changes

**Pull request closed without merging**
