### PR TITLE
Update SimpleSnake to AXIS

### PR DESCRIPTION
**Pull request by aismann**
THIS PROJECT IS IN DEVELOPMENT MODE. Any pull requests should merge to branch `dev`, otherwise will be rejected immediately.

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by aismann** [comment]
AXIS image (Draft) is better as the old ADXE, so I replaced it too

**Comment by aismann** [comment]
@halx99,
Maybe its time to move the example (SimpleSnake) to my own repository and remove the `example `folder from axis?
A link here should be enough.
https://github.com/axis-project/axis/discussions/694

**Comment by halx99** [comment]
> @halx99, Maybe its time to move the example (SimpleSnake) to my own repository and remove the `example `folder from axis? A link here should be enough. #694

ok

**Comment by halx99** [comment]
Add a link .md at root of engine maybe better, such `Related.md`

**Pull request closed without merging**
