### PR TITLE
Rename tests, extensions and configs

### PR DESCRIPTION
**Pull request by DelinWorks**
## Describe your changes
Refer to #724

### CODE REVIEW

**Comment by DelinWorks** [comment]
`Search "adxe" (0 hits in 0 files of 7993 searched)` done! there are no occurrences of `adxe` in the entire engine folder

**Comment by halx99** [comment]
Please prefer follow setp for any PRs yo avoid unexpect behavior, once new branch created, don't use merge from your branch `migrate-engine-name`, just copy modified files from it into new branch.

```sh
# Goto your local repo dir
cd axis
# add a remote name `official`
git remote add official https://github.com/axis-project/axis.git
# fetch remote `official`
git fetch official
# create new branch named `my-feature` from branch `official/dev`
git checkout -b my-feature official/dev

# do your modifications in branch `my-feature`

# commit and push your modifications branch my-feature to your own github repo
git add . && git commit -m "Example commit message"
git push origin my-feature

# Then you can goto upstream github webpage to create the PR with your plain branch `my-feature`
```

**Comment by DelinWorks** [comment]
But you can merge it right? don't worry I just accidentally merged in the wrong branch and undoing this is pain

**Comment by halx99** [comment]
Close as #739

**Pull request closed without merging**
