### PR TITLE
Replace everything under `core`

### PR DESCRIPTION
**Pull request by DelinWorks**
Refer to #733

### CODE REVIEW

**Comment by halx99** [comment]
Maybe your step still incorrect

**Comment by halx99** [comment]
> Maybe your step still incorrect

It looks like you create the branch from your own branch `dev`, not upstream `dev`?

**Comment by halx99** [comment]
> I've merged `migrate-engine-name` into `migrate-engine-name-2` and created a PR

It will inhert the commit history

**Comment by halx99** [comment]
I viewed the changes file, this branch looks correct

**Comment by DelinWorks** [comment]
> 

nice

**Comment by halx99** [comment]
There is a way to merge all commit into one:
```sh
# find the latest commit hash of upstream `dev`
git log

# reset with local changes reverts to the hash
git reset --soft <latest commit hash of upstream dev>

# Now you can only add on commit to your local branch
git commit -m "Example commit message"
```

And you don't do this, I will use `Squash and merge` button to erase unnecessary commits history by github automatically.
image

**Comment by DelinWorks** [comment]
`Search "adxe" (0 hits in 0 files of 1251 searched)` done with `core` you can merge now.

**Comment by halx99** [comment]
And the android ci failed because you change the engine adxetools.gradle which is depended by all tests & template projects

**Pull request merged**
